#------------------------------------------------\u670D\u52A1\u5668\u914D\u7F6E---------------------------------------
#\u670D\u52A1\u7AEF\u53E3
server:
  port: 18761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:18761/eureka/

  server:
    wait-time-in-ms-when-sync-empty: 0

spring:
  zipkin:
    # zipkin - 服务端地址
    base-url: http://192.168.31.210:9411/
  # zipkin 采样比例，0 - 1.0
  sleuth:
    sampler:
      percentage: 1.0

