server:
  port: 18888

spring:
  application:
    name: kjetboy-crawler
  datasource:
    url: jdbc:mysql://192.168.8.88:3307/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root