server:
  port: 18888

spring:
  application:
    name: kjetboy-crawler
  datasource:
    url: jdbc:mysql://localhost:13306/repair?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: Star*2020

mybatis-plus:
  global-config:
    db-config:
      id-type=none: none
  mapper-locations: classpath*:com/cloud/kjetboy/server/crawler/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl