server:
  port: 18886

cloud:
  audit:
    enabled: true


spring:
  application:
    name: cloud-kjetboy-demo
  datasource:
    url: jdbc:mysql://localhost:13306/repair?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: Star*2020
#  zipkin:
#    # zipkin - 服务端地址
#    base-url: http://127.0.0.1:19411
#  # zipkin 采样比例，0 - 1.0
#  sleuth:
#    sampler:
#      percentage: 1.0
mybatis-plus:
  global-config:
    db-config:
      id-type=none: none
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl